insert into test_messages (message) values('Hello')
insert into test_messages (message) values('World')
insert into store (category, item, stock) values ('books', 'ISBN1', 10)
insert into store (category, item, stock) values ('books', 'ISBN2', 20)
insert into store (category, item, stock) values ('books', 'ISBN3', 30)
insert into store (category, item, stock) values ('books', 'ISBN4', 5)
