insert into STORE (category, item , stock) values ('books', 'ISBN1', 42)
insert into STORE (category, item , stock) values ('books', 'ISBN2', 4)
insert into STORE (category, item , stock) values ('books', 'ISBN3', 2)
insert into STORE (category, item , stock) values ('books', 'ISBN4', 24)
insert into STORE (category, item , stock) values ('books', 'ISBN5', 44)