storeService.defaultStock=42
isbngenerator.prefix:ISBN:
isbngenerator.countryCode=-dk
idGenerator.start=1
server.port=9090
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:testdb
management.endpoints.web.exposure.include=health,prometheus,beans
management.metrics.export.prometheus.enabled=true