insert into messages (message) values ('Hello')
insert into Store (category, item, stock) values ('books', 'ISBN1', 42)
insert into Store (category, item, stock) values ('books', 'ISBN2', 9)
insert into keys values(0)
insert into Book (isbn, title, price) values('ISBN1', 'Title', 9.99)
