insert into store (category, item_id, stock) values ('books', 'Isbn1', 42)
insert into store (category, item_id, stock) values ('books', 'Isbn2', 2)
insert into store (category, item_id, stock) values ('books', 'Isbn3', 4)
insert into store (category, item_id, stock) values ('books', 'Isbn4', 1)
insert into id values (0)